config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"

  post "tasks", to: "tasks#create"
  get "tasks/new", to: "tasks#new", as: "new_task"

  get "tasks/:id", to: "tasks#show", as: "task"

  get "tasks/:id/edit", to: "tasks#edit", as: "task_edit"
  patch "tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy"

  # resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>

  <body>
    <div class="wrapper">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-sm-offset-3">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :name %>
  <%= t.text_field :name %>
  <%= t.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<ul>
  <% @tasks.each do |t| %>
  <li><%= t.done ? "[X]" : "[ ]" %> - <%= link_to t.name, task_path(t) %></li>
  <% end %>
</ul>

<%= link_to "Add a new task", new_task_path, class: "btn btn-primary"  %>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<p>
  <%= @task.done ? "[X]" : "[ ]" %><%= @task.name  %>
</p>
<%= link_to "/home", tasks_path %>
<%= link_to "Mark as done", task_path(task: { done: true}), method: :patch %>
<%= link_to "Edit task", task_edit_path %>
<%= link_to "Delete task", task_path, method: :delete, data: { confirm: 'Confirm delete ?' } %>